services:
  - type: web
    name: quantacare
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        value: us-east-1
      - key: PINECONE_INDEX_NAME
        value: quantacare-clinical-vectors
